[[redirects]]
  from = "/api/*"
  to = "https://672e1dd5229a881691ef09f0.mockapi.io/api/:splat"
  status = 200

[build]
  base = "assignment5-2"
  publish = "build"
  command = "CI=false npm run build"

[environment]
  REACT_APP_API_BASE_URL = "https://672e1dd5229a881691ef09f0.mockapi.io/api"